# Generated by Django 3.1.7 on 2021-03-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyberparlement',
            fields=[
                ('idcyberparlement', models.AutoField(db_column='idCyberParlement', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=45)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=200, null=True)),
                ('visibilite', models.CharField(blank=True, db_column='Visibilite', max_length=45, null=True)),
                ('cpparent', models.ForeignKey(blank=True, db_column='CPParent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.cyberparlement')),
            ],
            options={
                'db_table': 'cyberparlement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('idelection', models.AutoField(db_column='idElection', primary_key=True, serialize=False)),
                ('echeance', models.DateTimeField(blank=True, db_column='Echeance', null=True)),
                ('sujet', models.CharField(blank=True, db_column='Sujet', max_length=100, null=True)),
            ],
            options={
                'db_table': 'election',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genrepersonne',
            fields=[
                ('genre', models.CharField(db_column='Genre', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genrepersonne',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modevalidation',
            fields=[
                ('modevaltexte', models.CharField(db_column='ModeValTexte', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'modevalidation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rolemembrecp',
            fields=[
                ('rolecp', models.CharField(db_column='RoleCP', max_length=45, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'rolemembrecp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statutensemble',
            fields=[
                ('statuttexte', models.CharField(db_column='StatutTexte', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'statutensemble',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statutinitiative',
            fields=[
                ('statuttexte', models.CharField(db_column='StatutTexte', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'statutinitiative',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statutpersonne',
            fields=[
                ('statuttexte', models.CharField(db_column='StatutTexte', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'statutpersonne',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idforum', models.OneToOneField(db_column='idForum', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='djangoProject.cyberparlement')),
                ('idensemble', models.IntegerField(blank=True, db_column='idEnsemble', null=True)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=45, null=True)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=45, null=True)),
            ],
            options={
                'db_table': 'forum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idpersonne', models.AutoField(db_column='idPersonne', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='Nom', max_length=45)),
                ('prenom', models.CharField(db_column='Prenom', max_length=45)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=45, null=True)),
                ('npa', models.IntegerField(blank=True, db_column='NPA', null=True)),
                ('localite', models.CharField(db_column='Localite', max_length=45)),
                ('datenaissance', models.DateField(blank=True, db_column='DateNaissance', null=True)),
                ('notel', models.CharField(blank=True, db_column='NoTel', max_length=45, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
                ('genre', models.ForeignKey(blank=True, db_column='Genre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.genrepersonne')),
                ('statut', models.ForeignKey(blank=True, db_column='Statut', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.statutpersonne')),
            ],
            options={
                'db_table': 'personne',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('idinitiative', models.AutoField(db_column='idInitiative', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=45, null=True)),
                ('description', models.CharField(db_column='Description', max_length=1000)),
                ('echeance', models.DateTimeField(db_column='Echeance')),
                ('idcp', models.ForeignKey(db_column='idCP', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.cyberparlement')),
                ('idinitiateur', models.ForeignKey(blank=True, db_column='idInitiateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.personne')),
                ('modevalidation', models.ForeignKey(blank=True, db_column='ModeValidation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.modevalidation')),
                ('statut', models.ForeignKey(blank=True, db_column='Statut', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.statutinitiative')),
            ],
            options={
                'db_table': 'initiative',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cyberparlement',
            name='statut',
            field=models.ForeignKey(blank=True, db_column='Statut', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.statutensemble'),
        ),
        migrations.CreateModel(
            name='Choixinitiative',
            fields=[
                ('idchoixinitiative', models.AutoField(db_column='idChoixInitiative', primary_key=True, serialize=False)),
                ('choix', models.CharField(blank=True, db_column='Choix', max_length=45, null=True)),
                ('ordre', models.IntegerField(blank=True, db_column='Ordre', null=True)),
                ('idinitiative', models.ForeignKey(db_column='idInitiative', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.initiative')),
            ],
            options={
                'db_table': 'choixinitiative',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('idcandidat', models.AutoField(db_column='idCandidat', primary_key=True, serialize=False)),
                ('idelection', models.ForeignKey(db_column='idElection', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.election')),
                ('idpersonne', models.ForeignKey(db_column='idPersonne', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.personne')),
            ],
            options={
                'db_table': 'candidat',
                'managed': True,
                'unique_together': {('idelection', 'idpersonne')},
            },
        ),
        migrations.CreateModel(
            name='Voteinitiative',
            fields=[
                ('idvoteinitiative', models.AutoField(db_column='idVoteInitiative', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
                ('choixinitiative', models.ForeignKey(blank=True, db_column='idChoixInitiative', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.choixinitiative')),
                ('initiative', models.ForeignKey(db_column='idInitiative', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.initiative')),
                ('personne', models.ForeignKey(db_column='idPersonne', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.personne')),
            ],
            options={
                'db_table': 'voteinitiative',
                'managed': True,
                'unique_together': {('personne', 'initiative')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idmessage', models.AutoField(db_column='idMessage', primary_key=True, serialize=False)),
                ('contenu', models.CharField(blank=True, db_column='Contenu', max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('auteur', models.ForeignKey(blank=True, db_column='idAuteur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.personne')),
                ('forum', models.ForeignKey(blank=True, db_column='idForum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.forum')),
            ],
            options={
                'db_table': 'message',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membrecp',
            fields=[
                ('idmembrecp', models.AutoField(db_column='idMembreCP', primary_key=True, serialize=False)),
                ('cyberparlement', models.ForeignKey(db_column='idCyberParlement', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.cyberparlement')),
                ('personne', models.ForeignKey(db_column='idPersonne', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.personne')),
                ('roleCyberparlement', models.ForeignKey(db_column='RoleCP', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.rolemembrecp')),
            ],
            options={
                'db_table': 'membrecp',
                'managed': True,
                'unique_together': {('idmembrecp', 'personne')},
            },
        ),
        migrations.CreateModel(
            name='Voteelection',
            fields=[
                ('idelection', models.OneToOneField(db_column='idElection', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='djangoProject.election')),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('candidat', models.ForeignKey(blank=True, db_column='idCandidat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.candidat')),
                ('personne', models.ForeignKey(db_column='idPersonne', on_delete=django.db.models.deletion.DO_NOTHING, to='djangoProject.personne')),
            ],
            options={
                'db_table': 'voteelection',
                'managed': True,
                'unique_together': {('idelection', 'personne')},
            },
        ),
    ]
