# Generated by Django 3.1.7 on 2021-03-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='address_check',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='mail_check',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='password_check',
        ),
    ]
