# Generated by Django 3.1.7 on 2021-03-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_auto_20210311_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='addresscheck',
        ),
    ]
