# Generated by Django 3.1.7 on 2021-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_remove_personne_addresscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='addresscheck',
            field=models.CharField(blank=True, db_column='AddresseCheck', max_length=45, null=True),
        ),
    ]
