# Generated by Django 3.1.7 on 2021-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0005_personne_addresscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutpersonne',
            name='statut',
            field=models.CharField(blank=True, db_column='Statut', max_length=45, null=True),
        ),
    ]
