# Generated by Django 3.1.7 on 2021-03-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0006_statutpersonne_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statutpersonne',
            name='statut',
        ),
    ]
