# Generated by Django 3.1.7 on 2021-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0007_remove_statutpersonne_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutpersonne',
            name='statut',
            field=models.CharField(blank=True, db_column='Statut', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='statutpersonne',
            name='statuttexte',
            field=models.AutoField(db_column='StatutTexte', primary_key=True, serialize=False),
        ),
    ]
