# Generated by Django 3.1.7 on 2021-03-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0008_auto_20210316_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='statut',
        ),
        migrations.DeleteModel(
            name='Statutpersonne',
        ),
    ]
