# Generated by Django 3.1.7 on 2021-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0009_auto_20210316_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statutpersonne',
            fields=[
                ('statuttexte', models.AutoField(db_column='idStatutpersonne', primary_key=True, serialize=False)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=45, null=True)),
            ],
            options={
                'db_table': 'statutpersonne',
                'managed': True,
            },
        ),
    ]
