# Generated by Django 3.1.7 on 2021-03-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0010_statutpersonne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statutpersonne',
            old_name='statuttexte',
            new_name='idstatut',
        ),
    ]
